apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1USXhNakUwTWpreE1sb1hEVE0xTVRJeE1ERTBNamt4TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXpSCmRzNmNxcnMyWlVOK21GSWxXWldsVXRCNlk5MW5lN2kxY0tGcUZLTWJMM082aE9meGlUenZKRXdlWVF3WVNoMU4KVzlVSGFxUGJRenhVUXlrOUZMSjdMUkZXNVkrRTU0NExIWTZ3M2lKT0RaRVQ2TW1DdVdMTldLemVHWm93MCtPRwpMUWlJK3dwV281eWZDRmRkK3hFdGsxQU9XeWIxcERDaENWZktWR1VRTHZiL0lCQUpGR2lIQkNJSTNtRkE3RngzCkFvdjZLZlVqenFiOG9FK3gvYlE2ZzdWeWQ2TDFWcmVhZDBaWWpHT2ljZDdOcTVIdklIRjJvclZpekp2NjcwcmEKKzB1Qmt5T0ViSng5MktjRmJNMXNnMlg2RTIvcGpCK1BjVXR3aTJ6cjlmc0pYTmFXaFkyV0VYZkZLam02TXJvTQp6bnd2VU83L0FlcEI3b2puVVUwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIcDlydGxGZ0NiRGo4RkYxMU05TmdJR0NBVXRNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDQlMzTThkMXh1d0NnNG9DYXUvOXR6emNqR1QrUHp5VWFJYVBibnNxM3NXRU5JSCtmVApxYk5uMTcxSmZ4bWdHUEFSM2xTNGV1SVRRWjZXSXhTRkRNbHZBY0s4QlZkTmd5c2lDdTlFYUt6ekV4RW5kWWVDCmVhWmR0clFSUDhHTFFpZ3NjQ0JHcllRdkUrSG5QZDVwUXV5RW1mQWhuVndnT0NKWmlRNnRTdHpTSno0YjZReXgKL05WVk8waHBtb1NGWEJlYVUyWU9HcHBmbVQyQlhzZkQ0Q3FuSFFLV1NkM1craG5qWk9sL0duSlFSeUtqY1FwZgpjeHFhVzg0R0hFTjZRVUNaeUpaZnc2aUxLVVJ3R1lEZHh2YXMzbHpGQm1hMWRydVpiOFkzRStzVCthelhEV0tuClYvZHIvQjMrbU9Ea0VhcWZ4dHkwNzhGKzBSNU9XU25oSEZlZQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://178.154.227.166
  name: yc-managed-k8s-catdhhs3onc7qhq221uj
contexts:
- context:
    cluster: yc-managed-k8s-catdhhs3onc7qhq221uj
    user: yc-managed-k8s-catdhhs3onc7qhq221uj
  name: yc-perx-cluster
current-context: yc-perx-cluster
kind: Config
preferences: {}
users:
- name: yc-managed-k8s-catdhhs3onc7qhq221uj
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - k8s
      - create-token
      - --profile=default
      command: /usr/local/bin/yc
      env: null
      provideClusterInfo: false
