apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}-secret
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.env.MONGODB_URI | quote }}
  NATS_URL: {{ .Values.env.NATS_URL | quote }}
  PORT: {{ .Values.env.PORT | quote }}
